{"variants":[{"paths":["\/documentation\/mapboxcommon\/tileregionestimateresult\/init(errormargin:transfersize:storagesize:extradata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/tileregionestimateresult\/init(errormargin:transfersize:storagesize:extradata:)"]}],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/init(errorMargin:transferSize:storageSize:extraData:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult"]]},"metadata":{"roleHeading":"Initializer","role":"symbol","externalID":"c:objc(cs)MBXTileRegionEstimateResult(im)initWithErrorMargin:transferSize:storageSize:extraData:","symbolKind":"init","navigatorTitle":[{"text":"initWithErrorMargin:transferSize:storageSize:extraData:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"errorMargin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"transferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storageSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"text":"extraData","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"modules":[{"name":"MapboxCommon"}],"title":"init(errorMargin:transferSize:storageSize:extraData:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"errorMargin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"transferSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"storageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"extraData","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult/init(errorMargin:transferSize:storageSize:extraData:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"errorMargin","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"transferSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"storageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"extraData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult\/init(errorMargin:transferSize:storageSize:extraData:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithErrorMargin:transferSize:storageSize:extraData:"}],"title":"init(errorMargin:transferSize:storageSize:extraData:)","type":"topic","abstract":[],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult\/init(errormargin:transfersize:storagesize:extradata:)"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionEstimateResult":{"kind":"symbol","role":"symbol","title":"TileRegionEstimateResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileRegionEstimateResult","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionEstimateResult","abstract":[{"type":"text","text":"The result of tile region estim"}],"url":"\/documentation\/mapboxcommon\/tileregionestimateresult","navigatorTitle":[{"text":"TileRegionEstimateResult","kind":"identifier"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","kind":"article","type":"topic","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithErrorMargin:transferSize:storageSize:extraData:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithErrorMargin:transferSize:storageSize:extraData:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithErrorMargin:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"errorMargin","kind":"internalParam"},{"kind":"text","text":" "},{"text":"transferSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint64_t","preciseIdentifier":"c:@T@uint64_t","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"transferSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"storageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t","text":"uint64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"storageSize"},{"text":" ","kind":"text"},{"text":"extraData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"extraData","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1init(errorMargin:transferSize:storageSize:extraData:)\/title","value":"initWithErrorMargin:transferSize:storageSize:extraData:","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult~1init(errorMargin:transferSize:storageSize:extraData:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithErrorMargin:transferSize:storageSize:extraData:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/title","value":"MBXTileRegionEstimateResult"},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionEstimateResult"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/fragments"},{"value":[{"text":"MBXTileRegionEstimateResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionEstimateResult\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}