{"seeAlsoSections":[{"generated":true,"anchor":"Logs","title":"Logs","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:objc(pl)MBXLogWriterBackend","title":"LogWriterBackend","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogWriterBackend"}],"navigatorTitle":[{"text":"LogWriterBackend","kind":"identifier"}],"role":"symbol","modules":[{"name":"MapboxCommon"}],"symbolKind":"protocol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"LogWriterBackend","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend\/writeLog(for:message:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend"},"abstract":[{"text":"Interface for implementing log writing backends, e.g. for using platform specific log backends or logging to a notification service.","type":"text"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/mapboxcommon\/logwriterbackend"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/logwriterbackend"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogConfiguration":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","abstract":[{"text":"Class that allows to configure Mapbox SDKs logging per application.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"LogConfiguration"}],"role":"symbol","kind":"symbol","title":"LogConfiguration","url":"\/documentation\/mapboxcommon\/logconfiguration"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend/writeLog(for:message:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"writeLog","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LoggingLevel","preciseIdentifier":"c:@E@MBXLoggingLevel"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"writeLog(for:message:)","abstract":[{"type":"text","text":"Writes a log message with a given level."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend\/writeLog(for:message:)","role":"symbol","url":"\/documentation\/mapboxcommon\/logwriterbackend\/writelog(for:message:)","navigatorTitle":[{"kind":"identifier","text":"writeLogForLevel:message:"}],"type":"topic","required":true},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LogWriterBackend":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend","type":"topic","abstract":[{"text":"Interface for implementing log writing backends, e.g. for using platform specific log backends or logging to a notification service.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LogWriterBackend"}],"url":"\/documentation\/mapboxcommon\/logwriterbackend","role":"symbol","kind":"symbol","title":"LogWriterBackend","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogWriterBackend"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Performance":{"role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Performance","title":"Performance and investigations","url":"\/documentation\/mapboxmaps\/performance","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LoggingLevel":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel","type":"topic","abstract":[{"text":"State level of a log message.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LoggingLevel"}],"url":"\/documentation\/mapboxcommon\/logginglevel","role":"symbol","kind":"symbol","title":"LoggingLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LoggingLevel","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MBXLogWriterBackend"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXLogWriterBackend"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLogWriterBackend"}]},{"value":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogWriterBackend\/writeLog(for:message:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"generated":true,"anchor":"Logs","title":"Logs","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LogConfiguration","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LoggingLevel"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBXLogWriterBackend"}],"platforms":["iOS"]}]}},{"op":"replace","value":"MBXLogConfiguration","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/title"},{"value":[{"kind":"identifier","text":"MBXLogConfiguration"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogConfiguration\/navigatorTitle","value":[{"text":"MBXLogConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend~1writeLog(for:message:)\/title","value":"writeLogForLevel:message:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"writeLogForLevel:message:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend~1writeLog(for:message:)\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/title","value":"MBXLogWriterBackend","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBXLogWriterBackend"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LogWriterBackend\/navigatorTitle","value":[{"text":"MBXLogWriterBackend","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/title","value":"MBXLoggingLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/fragments","value":[{"text":"MBXLoggingLevel","kind":"identifier"}]},{"value":[{"text":"MBXLoggingLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LoggingLevel\/navigatorTitle"}]}]}