{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SettingsServiceStorageType","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/nonPersistent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/persistent"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/mapboxcommon\/settingsservicestoragetype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/settingsservicestoragetype"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}],"roleHeading":"Enumeration","symbolKind":"enum","modules":[{"name":"MapboxCommon"}],"role":"symbol","externalID":"c:@E@MBXSettingsServiceStorageType","title":"SettingsServiceStorageType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsServiceStorageType"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Enum that contains possible storage types that can be used for settings service.","type":"text"}],"seeAlsoSections":[{"title":"Common Settings","generated":true,"anchor":"Common-Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsService":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","abstract":[{"text":"Platform independent settings service. Settings service is a key\/value storage (persistent or non","type":"text"},{"type":"text","text":" "},{"type":"text","text":"persistent), that also allows to register observers to get notifications when values are updated."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsService"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsService"}],"role":"symbol","kind":"symbol","title":"SettingsService","url":"\/documentation\/mapboxcommon\/settingsservice"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SdkInformation":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation","type":"topic","abstract":[{"type":"text","text":"Provides information about a given Mapbox SDK. This information is then used to populate the “User-Agent” HTTP header"},{"type":"text","text":" "},{"text":"of HTTP requests generated from within Mapbox SDKs. Mapbox SDKs include Maps, Navigation, Search, and others.","type":"text"}],"navigatorTitle":[{"text":"SdkInformation","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/sdkinformation","role":"symbol","kind":"symbol","title":"SdkInformation","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SdkInformation","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/init(rawValue:)":{"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/init(rawvalue:)","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/init(rawValue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","kind":"symbol","title":"init(rawValue:)"},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/nonPersistent":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/nonPersistent","type":"topic","abstract":[{"type":"text","text":"Non persistent storage type means that all the settings will be only available during application lifetime and"},{"type":"text","text":" "},{"text":"will be destroyed on application exit.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypeNonPersistent"}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/nonpersistent","role":"symbol","kind":"symbol","title":"SettingsServiceStorageType.nonPersistent","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonPersistent"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/Equatable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","title":"Equatable Implementations","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/equatable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceFactory":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","type":"topic","abstract":[{"type":"text","text":"Factory that allows to create settings service instance."}],"navigatorTitle":[{"text":"SettingsServiceFactory","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservicefactory","role":"symbol","kind":"symbol","title":"SettingsServiceFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsServiceFactory"}]},"doc://com.mapbox.MapboxMaps/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","type":"topic","title":"SettingsServiceStorageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SettingsServiceStorageType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","kind":"symbol","abstract":[{"text":"Enum that contains possible storage types that can be used for settings service.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}]},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceError":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceError","abstract":[{"type":"text","text":"Structure for keeping an information about errors that can happen when using Settings service"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsServiceError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceError"}],"role":"symbol","kind":"symbol","title":"SettingsServiceError","url":"\/documentation\/mapboxcommon\/settingsserviceerror"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","url":"\/documentation\/mapboxmaps\/settings-and-constants","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","title":"Settings and Constants"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/persistent":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/persistent","abstract":[{"type":"text","text":"Persistent storage type means that all the settings key\/value pairs, that are set during application lifetime,"},{"text":" ","type":"text"},{"text":"will be available also after application gets terminated on the next run. On mobile platforms since we are","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"using system APIs all the settings will be also migrated to other user’s device with the same application"},{"type":"text","text":" "},{"type":"text","text":"install."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"persistent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypePersistent"}],"role":"symbol","kind":"symbol","title":"SettingsServiceStorageType.persistent","url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/persistent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MBXSettingsServiceStorageType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageType"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/nonPersistent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/persistent"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":[{"title":"Common Settings","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsService","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceFactory","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SdkInformation"],"anchor":"Common-Settings","generated":true}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBXSettingsServiceStorageType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/title","value":"MBXSettingsService"},{"value":[{"text":"MBXSettingsService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/fragments"},{"value":[{"text":"MBXSettingsService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsService\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/title","value":"MBXSdkInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/fragments","value":[{"text":"MBXSdkInformation","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXSdkInformation"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SdkInformation\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1nonPersistent\/title","op":"replace","value":"MBXSettingsServiceStorageTypeNonPersistent"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1nonPersistent\/fragments","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypeNonPersistent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/title","value":"MBXSettingsServiceFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/fragments","value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsServiceFactory"}]},{"value":"MBXSettingsServiceStorageType","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1persistent\/title","value":"MBXSettingsServiceStorageTypePersistent","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1persistent\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypePersistent"}]}]}]}