{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/tapinteraction\/init(_:filter:action:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TapInteraction\/init(_:filter:action:)","interfaceLanguage":"swift"},"abstract":[{"text":"Creates a Tap interaction on the specified featureset.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"featureset"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor","text":"FeaturesetDescriptor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"filter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Exp","text":"Exp"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature","kind":"typeIdentifier","text":"InteractiveFeature","preciseIdentifier":"s:10MapboxMaps18InteractiveFeatureC"},{"kind":"text","text":", "},{"preciseIdentifier":"s:10MapboxMaps18InteractionContextV","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractionContext","text":"InteractionContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A featureset descriptor denoting the featureset id or layer."}]}],"name":"featureset"},{"name":"filter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional filter of features that should trigger the interaction."}]}]},{"name":"action","content":[{"inlineContent":[{"type":"text","text":"An interaction action."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The interactions are handled in the features rendering order."},{"type":"text","text":" "},{"text":"If one feature handles multiple interactions, the last-added interaction is called first.","type":"text"}]},{"inlineContent":[{"type":"text","text":"If the "},{"type":"codeVoice","code":"action"},{"text":" returns ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" as a default, the interaction stops propagation."}],"type":"paragraph"}]}],"metadata":{"externalID":"s:10MapboxMaps14TapInteractionV_6filter6actionACSo23MBMFeaturesetDescriptorC_AA3ExpVSgSbAA18InteractiveFeatureC_AA0D7ContextVtctcfc","symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(_:filter:action:)","modules":[{"name":"MapboxMaps"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FeaturesetDescriptor","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor"},{"kind":"text","text":", "},{"text":"filter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Exp","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps3ExpV"},{"text":"?, ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps18InteractiveFeatureC","text":"InteractiveFeature"},{"text":", ","kind":"text"},{"text":"InteractionContext","kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps18InteractionContextV"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"tags":[{"type":"spi","text":"SPI"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TapInteraction"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TapInteraction":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TapInteraction","abstract":[{"text":"A single tap interaction.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"TapInteraction","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tapinteraction","title":"TapInteraction","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TapInteraction","kind":"identifier"}],"tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TapInteraction/init(_:filter:action:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TapInteraction\/init(_:filter:action:)","abstract":[{"text":"Creates a Tap interaction on the specified featureset.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMFeaturesetDescriptor","text":"FeaturesetDescriptor"},{"text":", ","kind":"text"},{"text":"filter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10MapboxMaps3ExpV","kind":"typeIdentifier","text":"Exp"},{"text":"?, ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:10MapboxMaps18InteractiveFeatureC","text":"InteractiveFeature"},{"kind":"text","text":", "},{"text":"InteractionContext","preciseIdentifier":"s:10MapboxMaps18InteractionContextV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/mapboxmaps\/tapinteraction\/init(_:filter:action:)","title":"init(_:filter:action:)","kind":"symbol","role":"symbol","tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractionContext":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractionContext","url":"\/documentation\/mapboxmaps\/interactioncontext","kind":"symbol","abstract":[{"type":"text","text":"A structure that defines context information for an interaction."}],"navigatorTitle":[{"text":"InteractionContext","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InteractionContext","kind":"identifier"}],"type":"topic","title":"InteractionContext"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/InteractiveFeature":{"navigatorTitle":[{"kind":"identifier","text":"InteractiveFeature"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InteractiveFeature"}],"abstract":[{"type":"text","text":"An interactive feature."}],"tags":[{"type":"spi","text":"SPI"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/InteractiveFeature","url":"\/documentation\/mapboxmaps\/interactivefeature","title":"InteractiveFeature","type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Featuresets-and-Interactions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Featuresets-and-Interactions","abstract":[{"type":"text","text":"The experimental Interactions API."}],"type":"topic","url":"\/documentation\/mapboxmaps\/featuresets-and-interactions","title":"Featuresets and Interactions","kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/FeaturesetDescriptor":{"abstract":[{"type":"text","text":"Represents an identifier for a single exported featureset or a layer."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FeaturesetDescriptor","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"FeaturesetDescriptor","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/FeaturesetDescriptor","url":"\/documentation\/mapboxmaps\/featuresetdescriptor","navigatorTitle":[{"kind":"identifier","text":"FeaturesetDescriptor"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Exp":{"url":"\/documentation\/mapboxmaps\/exp","abstract":[{"type":"text","text":"An "},{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Exp","type":"reference","isActive":true},{"text":"(expression) defines a formula for computing the value of any layout property, paint property,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or filter within a map style. Expressions allow you to style data with multiple feature"},{"text":" ","type":"text"},{"text":"properties at once, apply conditional logic, and manipulate data with mathematical, logical, and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"string operators. This allows for sophisticated runtime styling."}],"navigatorTitle":[{"kind":"identifier","text":"Exp"}],"kind":"symbol","title":"Exp","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Exp","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Exp"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/title","value":"MBMFeaturesetDescriptor"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/fragments","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1FeaturesetDescriptor\/navigatorTitle","value":[{"text":"MBMFeaturesetDescriptor","kind":"identifier"}]}]}]}