{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonPersistent"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Non persistent storage type means that all the settings will be only available during application lifetime and","type":"text"},{"text":" ","type":"text"},{"text":"will be destroyed on application exit.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/settingsservicestoragetype\/nonpersistent"]},{"paths":["\/documentation\/mapboxcommon\/settingsservicestoragetype\/nonpersistent"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@E@MBXSettingsServiceStorageType@MBXSettingsServiceStorageTypeNonPersistent","symbolKind":"case","navigatorTitle":[{"text":"MBXSettingsServiceStorageTypeNonPersistent","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonPersistent"}],"title":"SettingsServiceStorageType.nonPersistent","modules":[{"name":"MapboxCommon"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/nonPersistent"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType/nonPersistent":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType\/nonPersistent","type":"topic","abstract":[{"type":"text","text":"Non persistent storage type means that all the settings will be only available during application lifetime and"},{"type":"text","text":" "},{"text":"will be destroyed on application exit.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypeNonPersistent"}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype\/nonpersistent","role":"symbol","kind":"symbol","title":"SettingsServiceStorageType.nonPersistent","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonPersistent"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/SettingsServiceStorageType":{"role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/SettingsServiceStorageType","type":"topic","title":"SettingsServiceStorageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SettingsServiceStorageType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/settingsservicestoragetype","kind":"symbol","abstract":[{"text":"Enum that contains possible storage types that can be used for settings service.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SettingsServiceStorageType"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Settings-and-Constants":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Settings-and-Constants","url":"\/documentation\/mapboxmaps\/settings-and-constants","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","title":"Settings and Constants"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBXSettingsServiceStorageTypeNonPersistent","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypeNonPersistent"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypeNonPersistent"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MBXSettingsServiceStorageTypeNonPersistent","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1nonPersistent\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType~1nonPersistent\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXSettingsServiceStorageTypeNonPersistent"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/title","op":"replace","value":"MBXSettingsServiceStorageType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/fragments","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1SettingsServiceStorageType\/navigatorTitle","value":[{"text":"MBXSettingsServiceStorageType","kind":"identifier"}]}]}]}