{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionloadprogress\/init(completedresourcecount:completedresourcesize:erroredresourcecount:requiredresourcecount:loadedresourcecount:loadedresourcesize:)"]},{"paths":["\/documentation\/mapboxcommon\/tileregionloadprogress\/init(completedresourcecount:completedresourcesize:erroredresourcecount:requiredresourcecount:loadedresourcecount:loadedresourcesize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress\/init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"completedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"text":"completedResourceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"erroredResourceCount"},{"kind":"text","text":": "},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"loadedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"loadedResourceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Initializer","title":"init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"completedResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completedResourceSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"erroredResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"text":"requiredResourceCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":", "},{"text":"loadedResourceCount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier","text":"UInt64"},{"kind":"text","text":", "},{"text":"loadedResourceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"text":")","kind":"text"}],"modules":[{"name":"MapboxCommon"}],"navigatorTitle":[{"text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)MBXTileRegionLoadProgress(im)initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","symbolKind":"init"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress":{"type":"topic","role":"symbol","title":"TileRegionLoadProgress","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileRegionLoadProgress"}],"url":"\/documentation\/mapboxcommon\/tileregionloadprogress","kind":"symbol","abstract":[{"text":"A tile region’s load progress includes counts","type":"text"},{"type":"text","text":" "},{"text":"of the number of resources that have completed downloading","type":"text"},{"text":" ","type":"text"},{"text":"and the total number of resources that are required.","type":"text"}],"navigatorTitle":[{"text":"TileRegionLoadProgress","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionLoadProgress/init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)":{"url":"\/documentation\/mapboxcommon\/tileregionloadprogress\/init(completedresourcecount:completedresourcesize:erroredresourcecount:requiredresourcecount:loadedresourcecount:loadedresourcesize:)","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionLoadProgress\/init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:"}],"title":"init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completedResourceCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completedResourceSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"kind":"text","text":", "},{"text":"erroredResourceCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V","text":"UInt64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"requiredResourceCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadedResourceCount"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"},{"text":", ","kind":"text"},{"text":"loadedResourceSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","url":"\/documentation\/mapboxmaps\/tilestore-apis","title":"TileStore APIs","kind":"article","type":"topic","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"initWithCompletedResourceCount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t","text":"uint64_t"},{"kind":"text","text":") "},{"text":"completedResourceCount","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completedResourceSize:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"uint64_t","preciseIdentifier":"c:@T@uint64_t"},{"kind":"text","text":") "},{"text":"completedResourceSize","kind":"internalParam"},{"kind":"text","text":" "},{"text":"erroredResourceCount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t","text":"uint64_t"},{"kind":"text","text":") "},{"text":"erroredResourceCount","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredResourceCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"requiredResourceCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"loadedResourceCount:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t","text":"uint64_t"},{"text":") ","kind":"text"},{"text":"loadedResourceCount","kind":"internalParam"},{"kind":"text","text":" "},{"text":"loadedResourceSize:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint64_t","text":"uint64_t"},{"text":") ","kind":"text"},{"text":"loadedResourceSize","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/title","value":"MBXTileRegionLoadProgress"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBXTileRegionLoadProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress\/navigatorTitle","value":[{"text":"MBXTileRegionLoadProgress","kind":"identifier"}]},{"op":"replace","value":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress~1init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionLoadProgress~1init(completedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCompletedResourceCount:completedResourceSize:erroredResourceCount:requiredResourceCount:loadedResourceCount:loadedResourceSize:","kind":"identifier"}]}]}]}