{"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/removeLocationObserver(for:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"s:10MapboxMaps21AppleLocationProviderC06removeD8Observer3forySo011MBXLocationG0_p_tF","extendedModule":"MapboxMaps","title":"removeLocationObserver(for:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeLocationObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MBXLocationObserver","kind":"typeIdentifier","text":"LocationObserver"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"MapboxMaps"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/LocationProvider-Implementations"]]},"abstract":[{"text":"Removes the location observer","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeLocationObserver","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MBXLocationObserver","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","text":"LocationObserver"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"When the last observer is gone, the underlying ","type":"text"},{"type":"codeVoice","code":"CLLocationManager"},{"text":" it will stop location updates.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/applelocationprovider\/removelocationobserver(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider/removeLocationObserver(for:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/removeLocationObserver(for:)","title":"removeLocationObserver(for:)","url":"\/documentation\/mapboxmaps\/applelocationprovider\/removelocationobserver(for:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeLocationObserver"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)MBXLocationObserver","kind":"typeIdentifier","text":"LocationObserver"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Removes the location observer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider":{"type":"topic","kind":"symbol","title":"AppleLocationProvider","abstract":[{"type":"text","text":"A location provider based on CoreLocation’s "},{"type":"codeVoice","code":"CLLocationManager"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider","navigatorTitle":[{"kind":"identifier","text":"AppleLocationProvider"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AppleLocationProvider","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/applelocationprovider"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/LocationObserver":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/LocationObserver","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LocationObserver"}],"navigatorTitle":[{"text":"LocationObserver","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/locationobserver","abstract":[{"type":"text","text":"Observer for getting updates from a LocationProvider."}],"title":"LocationObserver"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/AppleLocationProvider/LocationProvider-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/AppleLocationProvider\/LocationProvider-Implementations","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/applelocationprovider\/locationprovider-implementations","title":"LocationProvider Implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Location-APIs":{"title":"Location","url":"\/documentation\/mapboxmaps\/location-apis","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Location-APIs","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/title","value":"MBXLocationObserver"},{"value":[{"text":"MBXLocationObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1LocationObserver\/navigatorTitle","value":[{"kind":"identifier","text":"MBXLocationObserver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}