{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/other"]},{"paths":["\/documentation\/mapboxcommon\/tileregionerrortype\/other"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Other reason."}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"other"}],"navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeOther"}],"title":"TileRegionErrorType.other","role":"symbol","roleHeading":"Case","modules":[{"name":"MapboxCommon"}],"externalID":"c:@E@MBXTileRegionErrorType@MBXTileRegionErrorTypeOther"},"sections":[],"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/other","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType/other":{"type":"topic","abstract":[{"type":"text","text":"Other reason."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"navigatorTitle":[{"kind":"identifier","text":"MBXTileRegionErrorTypeOther"}],"title":"TileRegionErrorType.other","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType\/other","role":"symbol","url":"\/documentation\/mapboxcommon\/tileregionerrortype\/other","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","url":"\/documentation\/mapboxcommon","abstract":[],"role":"collection","title":"MapboxCommon","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileRegionErrorType":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileRegionErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileRegionErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"TileRegionErrorType","kind":"identifier"}],"url":"\/documentation\/mapboxcommon\/tileregionerrortype","kind":"symbol","abstract":[{"text":"Describes the reason for a tile region download request failure.","type":"text"}],"role":"symbol","title":"TileRegionErrorType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MBXTileRegionErrorTypeOther"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBXTileRegionErrorTypeOther","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBXTileRegionErrorTypeOther","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1other\/title","value":"MBXTileRegionErrorTypeOther"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType~1other\/fragments","value":[{"kind":"identifier","text":"MBXTileRegionErrorTypeOther"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/title","value":"MBXTileRegionErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/fragments","value":[{"text":"MBXTileRegionErrorType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBXTileRegionErrorType"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileRegionErrorType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}