{"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ","doc:\/\/com.mapbox.MapboxMaps\/SH","doc:\/\/com.mapbox.MapboxMaps\/SY","doc:\/\/com.mapbox.MapboxMaps\/s8SendableP"],"title":"Conforms To"}],"seeAlsoSections":[{"generated":true,"anchor":"Sources","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"title":"Sources"}],"abstract":[{"type":"text","text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scheme"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"sections":[],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/rawValue"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/tms","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/xyz"],"generated":true},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/RawRepresentable-Implementations"]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/scheme"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Scheme","kind":"identifier"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"title":"Scheme","role":"symbol","externalID":"s:10MapboxMaps6SchemeV","modules":[{"name":"MapboxMaps"}],"roleHeading":"Structure"},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme/xyz":{"abstract":[{"type":"text","text":"Slippy map tilenames scheme."}],"url":"\/documentation\/mapboxmaps\/scheme\/xyz","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/xyz","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"xyz","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SchemeV","text":"Scheme","kind":"typeIdentifier"}],"title":"xyz","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"title":"GeoJSONSourceData","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GeoJSONSourceData"}],"abstract":[{"type":"text","text":"Captures potential values of the "},{"type":"codeVoice","code":"data"},{"text":" property of a GeoJSONSource.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSourceData","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","url":"\/documentation\/mapboxmaps\/rasterarraysource","kind":"symbol","abstract":[{"text":"A raster array source","type":"text"}],"navigatorTitle":[{"text":"RasterArraySource","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"RasterArraySource","kind":"identifier"}],"type":"topic","tags":[{"type":"spi","text":"SPI"}],"title":"RasterArraySource"},"doc://com.mapbox.MapboxMaps/SY":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.mapbox.MapboxMaps/s8SendableP":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme/rawValue":{"role":"symbol","kind":"symbol","title":"rawValue","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/rawValue","type":"topic","url":"\/documentation\/mapboxmaps\/scheme\/rawvalue","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","url":"\/documentation\/mapboxmaps\/geojsonsource","kind":"symbol","abstract":[{"text":"A GeoJSON data source.","type":"text"}],"navigatorTitle":[{"text":"GeoJSONSource","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeoJSONSource","kind":"identifier"}],"type":"topic","title":"GeoJSONSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","url":"\/documentation\/mapboxmaps\/scheme","kind":"symbol","abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}],"navigatorTitle":[{"text":"Scheme","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Scheme","kind":"identifier"}],"type":"topic","title":"Scheme"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"title":"PromoteId","role":"symbol","navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/promoteid","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PromoteId","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","url":"\/documentation\/mapboxmaps\/customgeometrysource","kind":"symbol","abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}],"navigatorTitle":[{"text":"CustomGeometrySource","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"type":"topic","title":"CustomGeometrySource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","kind":"symbol","abstract":[{"text":"Options for custom geometry source.","type":"text"}],"navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"type":"topic","title":"CustomGeometrySourceOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/SH":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme/Equatable-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/Equatable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/mapboxmaps\/scheme\/equatable-implementations","role":"collectionGroup","kind":"article","title":"Equatable Implementations"},"doc://com.mapbox.MapboxMaps/SE":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","title":"SourceType","url":"\/documentation\/mapboxmaps\/sourcetype","navigatorTitle":[{"kind":"identifier","text":"SourceType"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceType"}],"abstract":[{"type":"text","text":"Struct of supported Source Types"},{"type":"text","text":" "},{"type":"text","text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/"}]},"doc://com.mapbox.MapboxMaps/Se":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","url":"\/documentation\/mapboxmaps\/encoding","kind":"symbol","abstract":[{"text":"The encoding used by this source. Mapbox Terrain RGB is used by default","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Encoding"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Encoding"}],"type":"topic","title":"Encoding"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"title":"CustomRasterSourceTileRenderer","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileRenderer","kind":"identifier"}],"abstract":[{"type":"text","text":"Interface for the direct rendering into the custom raster tiles."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme/init(rawValue:)":{"abstract":[],"url":"\/documentation\/mapboxmaps\/scheme\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileFunctionCallback"}],"kind":"symbol","abstract":[{"type":"text","text":"Callback to do various operations for tile."},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"title":"TileFunctionCallback","url":"\/documentation\/mapboxmaps\/tilefunctioncallback","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TileFunctionCallback"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"title":"CustomRasterSourceTileStatus","role":"symbol","navigatorTitle":[{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"title":"Source","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Source"}],"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/source","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Source"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/mapboxmaps\/scheme\/rawrepresentable-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","role":"symbol","title":"CustomRasterSourceTileData","kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","navigatorTitle":[{"text":"CustomRasterSourceTileData","kind":"identifier"}],"abstract":[{"type":"text","text":"Data for a specific CustomRasterSource tile."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceTileData"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","type":"topic","title":"ImageSource","role":"symbol","abstract":[{"text":"An image data source.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSource"}],"url":"\/documentation\/mapboxmaps\/imagesource","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"title":"CustomRasterSourceOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"abstract":[{"type":"text","text":"Options for custom raster source."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceOptions","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"type":"topic","abstract":[{"type":"text","text":"A raster tile source."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","url":"\/documentation\/mapboxmaps\/rastersource","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RasterSource"}],"navigatorTitle":[{"kind":"identifier","text":"RasterSource"}],"title":"RasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme/tms":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tms","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10MapboxMaps6SchemeV","kind":"typeIdentifier","text":"Scheme"}],"type":"topic","url":"\/documentation\/mapboxmaps\/scheme\/tms","title":"tms","role":"symbol","abstract":[{"type":"text","text":"OSGeo spec scheme."}],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme\/tms"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"tags":[{"text":"SPI","type":"spi"}],"title":"CustomRasterSource","role":"symbol","navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/customrastersource","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"role":"symbol","title":"SourceInfo","abstract":[{"type":"text","text":"Information about a Source"}],"url":"\/documentation\/mapboxmaps\/sourceinfo","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceInfo"}],"navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","kind":"symbol","type":"topic"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","kind":"symbol","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}],"navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileStatusChangedCallback"}],"type":"topic","title":"CustomRasterSourceTileStatusChangedCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"type":"topic","url":"\/documentation\/mapboxmaps\/sources","title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceClient","kind":"identifier"}],"type":"topic","title":"CustomRasterSourceClient"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","url":"\/documentation\/mapboxmaps\/rasterdemsource","navigatorTitle":[{"kind":"identifier","text":"RasterDemSource"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterDemSource","kind":"identifier"}],"title":"RasterDemSource","abstract":[{"text":"A RGB-encoded raster DEM source","type":"text"}]},"doc://com.mapbox.MapboxMaps/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceClientType"}],"type":"topic","title":"CustomRasterSourceClientType"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","url":"\/documentation\/mapboxmaps\/vectorsource","kind":"symbol","abstract":[{"type":"text","text":"A vector tile source."}],"navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VectorSource"}],"type":"topic","title":"VectorSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"title":"TileCacheBudgetSize","role":"symbol","navigatorTitle":[{"text":"TileCacheBudgetSize","kind":"identifier"}],"abstract":[{"text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit.","type":"text"},{"text":" ","type":"text"},{"text":"Whenever tile cache goes over the defined limit","type":"text"},{"type":"text","text":" "},{"text":"the least recently used tile will be evicted from the in-memory cache","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TileCacheBudgetSize"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","op":"replace","value":"MBMCustomGeometrySourceOptions"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}]},{"op":"replace","value":"MBMCustomRasterSourceTileRenderer","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title","value":"MBMTileFunctionCallback"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title","value":"MBMCustomRasterSourceTileStatus"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","value":"MBMCustomRasterSourceTileData"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"value":[{"text":"MBMCustomRasterSourceTileData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle"},{"op":"replace","value":"MBMCustomRasterSourceOptions","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"op":"replace","value":"MBMCustomRasterSourceClient","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","value":"MBMCustomRasterSourceClientType"},{"value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments"},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}