{"metadata":{"modules":[{"name":"MapboxMaps"}],"fragments":[{"kind":"identifier","text":"constrainMode"}],"title":"constrainMode","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"constrainMode"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)MBMMapOptions(py)constrainMode"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/constrainMode"},"abstract":[{"text":"The map constrain mode. This can be used to limit the map","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to wrap around the globe horizontally. By default, it is set to"},{"type":"text","text":" "},{"code":"HeightOnly","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/mapboxmaps\/mbmmapoptions\/constrainmode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"constrainMode"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"title":"MapboxMaps Documentation","abstract":[],"url":"\/documentation\/overview","role":"collection","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","type":"topic","kind":"article"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","kind":"symbol","type":"topic","url":"\/documentation\/mapboxmaps","abstract":[{"text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal.","type":"text"}],"role":"collection","title":"MapboxMaps"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Map-View":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Map-View","kind":"article","abstract":[],"title":"MapView","role":"collectionGroup","url":"\/documentation\/mapboxmaps\/map-view"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapOptions":{"type":"topic","abstract":[{"text":"Describes the map option values.","type":"text"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapOptions","title":"MapOptions","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapOptions","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/mapoptions","navigatorTitle":[{"text":"MapOptions","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MBMMapOptions/constrainMode":{"url":"\/documentation\/mapboxmaps\/mbmmapoptions\/constrainmode","abstract":[{"text":"The map constrain mode. This can be used to limit the map","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to wrap around the globe horizontally. By default, it is set to"},{"type":"text","text":" "},{"code":"HeightOnly","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"constrainMode","kind":"identifier"}],"type":"topic","title":"constrainMode","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MBMMapOptions\/constrainMode"}},"variantOverrides":[{"patch":[{"value":"MBMMapOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/fragments","value":[{"text":"MBMMapOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBMMapOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1MapOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}